### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by hsyed** [kevoree-modeling/framework#3]
Is there an ETA to when the documentation be updated ?  I have been checking back regularly for weeks now.

**Comment by dukeboard** [comment]
Hello and thanks for your interest to Kevoree Modeling project. Currently the team is finishing the bunch of features planned for the v4 version. The documentation will follow two weeks later.

The development schedule of KMF will be:

End of the week: beta version 4(.20) of framework and IDEA plugin (full features, no doc)
End of the month: release version 
Mid august: release of the documentation and associated online tutorials.
End of august: release of new CDN WebRTC drivers
End of September: presentation at the models conference 2015 (Ottawa Canada)
End of October: presentation at the SmartGridComm conference 2015 (Miami US)

Best regards,
Francois Fouquet

**Comment by hsyed** [comment]
Many thanks for the update. I look forward to evaluating KMF.

**Comment by dukeboard** [comment]
New documentation is integrated into the new tutorial repository associated to this organisation
