### ISSUE TITLE
Rename npm module name for KMF

### ISSUE THREAD

**Issue by maxleiko** [kevoree-modeling/framework#6]
Npm module tends to be simple. Something like "kmf-umd" is way better than "org.kevoree.modeling.microframework.umd" here https://github.com/kevoree-modeling/framework/blob/master/org.kevoree.modeling.microframework.umd/src/main/resources/package.json for instance :)

**Comment by maxleiko** [comment]
Well, because KMF generate one big file now for .ts. It might be useless to keep this npm module though.

**Comment by dukeboard** [comment]
i will keep for pure reflexive usage, the API now can used without the code generation step
